[phases.setup]
nixpkgs = ["https://nixpkgs.com/nixpkgs-unstable"]

[phases.build]
nixpkgs = ["https://nixpkgs.com/nixpkgs-unstable"]
paths = ["../."]

[phases.install]
nixpkgs = ["https://nixpkgs.com/nixpkgs-unstable"]
paths = ["../."]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
